package edu.ilstu.biology.flytranscriptionwebapp.processor;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class RetrieveExpressionStages {

	@Autowired
	private ExpressionStageConverter expressionStageConverter;

	public List<String> getDmelanogasterExpressionStages() {
		List<String> expressionStages = new ArrayList<String>();

		/**
		 * @Generated by manualAddExpressionStages.py
		 */
		/* 0 */ expressionStages.add("4-day Adult, Caffeine 2.5mg/ml");
		/* 1 */ expressionStages.add("4-day Adult, Caffeine 25mg/ml");
		/* 2 */ expressionStages.add("4-day Adult, Cd 0.05M");
		/* 3 */ expressionStages.add("4-day Adult, Cd 0.1M");
		/* 4 */ expressionStages.add("4-day Adult, Cu 15mM");
		/* 5 */ expressionStages.add("4-day Adult, Paraquat 10mM");
		/* 6 */ expressionStages.add("4-day Adult, Paraquat 5mM");
		/* 7 */ expressionStages.add("4-day Adult, Zn 4.5mM");
		/* 8 */ expressionStages.add("4-day Adult, cold 1");
		/* 9 */ expressionStages.add("4-day Adult, cold 2");
		/* 10 */ expressionStages.add("4-day Adult, heatshock");
		/* 11 */ expressionStages.add("A 1d carcass");
		/* 12 */ expressionStages.add("A 1d dig sys");
		/* 13 */ expressionStages.add("A 20d carcass");
		/* 14 */ expressionStages.add("A 20d dig sys");
		/* 15 */ expressionStages.add("A 4d carcass");
		/* 16 */ expressionStages.add("A 4d dig sys");
		/* 17 */ expressionStages.add("A MateF 1d head");
		/* 18 */ expressionStages.add("A MateF 20d head");
		/* 19 */ expressionStages.add("A MateF 4d head");
		/* 20 */ expressionStages.add("A MateF 4d ovary");
		/* 21 */ expressionStages.add("A MateM 1d head");
		/* 22 */ expressionStages.add("A MateM 20d head");
		/* 23 */ expressionStages.add("A MateM 4d acc gland");
		/* 24 */ expressionStages.add("A MateM 4d head");
		/* 25 */ expressionStages.add("A MateM 4d testis");
		/* 26 */ expressionStages.add("A VirF 1d head");
		/* 27 */ expressionStages.add("A VirF 20d head");
		/* 28 */ expressionStages.add("A VirF 4d head");
		/* 29 */ expressionStages.add("A VirF 4d ovary");
		/* 30 */ expressionStages.add("CNS ML-DmBG1-c1");
		/* 31 */ expressionStages.add("CNS ML-DmBG2-c2");
		/* 32 */ expressionStages.add("L3 CNS");
		/* 33 */ expressionStages.add("L3 Wand carcass");
		/* 34 */ expressionStages.add("L3 Wand dig sys");
		/* 35 */ expressionStages.add("L3 Wand fat");
		/* 36 */ expressionStages.add("L3 Wand imag disc");
		/* 37 */ expressionStages.add("L3 Wand saliv");
		/* 38 */ expressionStages.add("P15");
		/* 39 */ expressionStages.add("P5");
		/* 40 */ expressionStages.add("P6");
		/* 41 */ expressionStages.add("P8");
		/* 42 */ expressionStages.add("P8 CNS");
		/* 43 */ expressionStages.add("P8 fat");
		/* 44 */ expressionStages.add("P9-10");
		/* 45 */ expressionStages.add("Schneider line 2 S2R+");
		/* 46 */ expressionStages.add("Schneider line 2 Sg4");
		/* 47 */ expressionStages.add("WPP fat");
		/* 48 */ expressionStages.add("WPP saliv");
		/* 49 */ expressionStages.add("adult female 01day");
		/* 50 */ expressionStages.add("adult female 05day");
		/* 51 */ expressionStages.add("adult female 30day");
		/* 52 */ expressionStages.add("adult male 01day");
		/* 53 */ expressionStages.add("adult male 05day");
		/* 54 */ expressionStages.add("adult male 30day");
		/* 55 */ expressionStages.add("antennal disc ML-DmD20-c5");
		/* 56 */ expressionStages.add("embryo 00-02hr");
		/* 57 */ expressionStages.add("embryo 02-04hr");
		/* 58 */ expressionStages.add("embryo 04-06hr");
		/* 59 */ expressionStages.add("embryo 06-08hr");
		/* 60 */ expressionStages.add("embryo 08-10hr");
		/* 61 */ expressionStages.add("embryo 10-12hr");
		/* 62 */ expressionStages.add("embryo 12-14hr");
		/* 63 */ expressionStages.add("embryo 14-16hr");
		/* 64 */ expressionStages.add("embryo 16-18hr");
		/* 65 */ expressionStages.add("embryo 18-20hr");
		/* 66 */ expressionStages.add("embryo 20-22hr");
		/* 67 */ expressionStages.add("embryo 22-24hr");
		/* 68 */ expressionStages.add("embryonic 1182-4H");
		/* 69 */ expressionStages.add("embryonic GM2");
		/* 70 */ expressionStages.add("embryonic Kc167");
		/* 71 */ expressionStages.add("embryonic S1");
		/* 72 */ expressionStages.add("embryonic S3");
		/* 73 */ expressionStages.add("eye-antennal disc ML-DmD11");
		/* 74 */ expressionStages.add("haltere disc ML-DmD17-c3");
		/* 75 */ expressionStages.add("larva L1");
		/* 76 */ expressionStages.add("larva L2");
		/* 77 */ expressionStages.add("larva L3 12hr old");
		/* 78 */ expressionStages.add("larva L3 late, Zn 5mM");
		/* 79 */ expressionStages.add("larva L3 puffstage 1-2");
		/* 80 */ expressionStages.add("larva L3 puffstage 3-6");
		/* 81 */ expressionStages.add("larva L3 puffstage 7-9");
		/* 82 */ expressionStages.add("larva L3, Caffeine 1.5mg/ml");
		/* 83 */ expressionStages.add("larva L3, Cd 12hr");
		/* 84 */ expressionStages.add("larva L3, Cd 6hr");
		/* 85 */ expressionStages.add("larva L3, Cu 0.5mM");
		/* 86 */ expressionStages.add("larva L3, EtOH 10");
		/* 87 */ expressionStages.add("larva L3, EtOH 2.5");
		/* 88 */ expressionStages.add("larva L3, EtOH 5");
		/* 89 */ expressionStages.add("larva L3, Rotenone 2?g");
		/* 90 */ expressionStages.add("larva L3, Rotenone 8?g");
		/* 91 */ expressionStages.add("leg disc CME L1");
		/* 92 */ expressionStages.add("mixed discs ML-DmD4-c1");
		/* 93 */ expressionStages.add("ovary OSC");
		/* 94 */ expressionStages.add("ovary OSS");
		/* 95 */ expressionStages.add("ovary fGS/OSS");
		/* 96 */ expressionStages.add("tumorous blood cells mbn2");
		/* 97 */ expressionStages.add("white prepupae new");
		/* 98 */ expressionStages.add("wing disc CME-W2");
		/* 99 */ expressionStages.add("wing disc ML-DmD16-c3");
		/* 100 */ expressionStages.add("wing disc ML-DmD21");
		/* 101 */ expressionStages.add("wing disc ML-DmD32");
		/* 102 */ expressionStages.add("wing disc ML-DmD8");
		/* 103 */ expressionStages.add("wing disc ML-DmD9");
		return expressionStageConverter.convertListofLabelsToId(expressionStages);
	}
}
