package edu.ilstu.biology.flytranscriptionwebapp.processor;

import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Component;

@Component
public class RetrieveExpressionStages {

	public List<String> getDmelanogasterExpressionStages() {
		List<String> expressionStages = new ArrayList<String>();

		/**
		 * @Generated by manualAddExpressionStages.py
		 */
		expressionStages.add("4-day Adult, Caffeine 2.5mg/ml");
		expressionStages.add("4-day Adult, Caffeine 25mg/ml");
		expressionStages.add("4-day Adult, Cd 0.05M");
		expressionStages.add("4-day Adult, Cd 0.1M");
		expressionStages.add("4-day Adult, Cu 15mM");
		expressionStages.add("4-day Adult, Paraquat 10mM");
		expressionStages.add("4-day Adult, Paraquat 5mM");
		expressionStages.add("4-day Adult, Zn 4.5mM");
		expressionStages.add("4-day Adult, cold 1");
		expressionStages.add("4-day Adult, cold 2");
		expressionStages.add("4-day Adult, heatshock");
		expressionStages.add("A 1d carcass");
		expressionStages.add("A 1d dig sys");
		expressionStages.add("A 20d carcass");
		expressionStages.add("A 20d dig sys");
		expressionStages.add("A 4d carcass");
		expressionStages.add("A 4d dig sys");
		expressionStages.add("A MateF 1d head");
		expressionStages.add("A MateF 20d head");
		expressionStages.add("A MateF 4d head");
		expressionStages.add("A MateF 4d ovary");
		expressionStages.add("A MateM 1d head");
		expressionStages.add("A MateM 20d head");
		expressionStages.add("A MateM 4d acc gland");
		expressionStages.add("A MateM 4d head");
		expressionStages.add("A MateM 4d testis");
		expressionStages.add("A VirF 1d head");
		expressionStages.add("A VirF 20d head");
		expressionStages.add("A VirF 4d head");
		expressionStages.add("A VirF 4d ovary");
		expressionStages.add("CNS ML-DmBG1-c1");
		expressionStages.add("CNS ML-DmBG2-c2");
		expressionStages.add("L3 CNS");
		expressionStages.add("L3 Wand carcass");
		expressionStages.add("L3 Wand dig sys");
		expressionStages.add("L3 Wand fat");
		expressionStages.add("L3 Wand imag disc");
		expressionStages.add("L3 Wand saliv");
		expressionStages.add("P15");
		expressionStages.add("P5");
		expressionStages.add("P6");
		expressionStages.add("P8");
		expressionStages.add("P8 CNS");
		expressionStages.add("P8 fat");
		expressionStages.add("P9-10");
		expressionStages.add("Schneider line 2 S2R+");
		expressionStages.add("Schneider line 2 Sg4");
		expressionStages.add("WPP fat");
		expressionStages.add("WPP saliv");
		expressionStages.add("adult female 01day");
		expressionStages.add("adult female 05day");
		expressionStages.add("adult female 30day");
		expressionStages.add("adult male 01day");
		expressionStages.add("adult male 05day");
		expressionStages.add("adult male 30day");
		expressionStages.add("antennal disc ML-DmD20-c5");
		expressionStages.add("embryo 00-02hr");
		expressionStages.add("embryo 02-04hr");
		expressionStages.add("embryo 04-06hr");
		expressionStages.add("embryo 06-08hr");
		expressionStages.add("embryo 08-10hr");
		expressionStages.add("embryo 10-12hr");
		expressionStages.add("embryo 12-14hr");
		expressionStages.add("embryo 14-16hr");
		expressionStages.add("embryo 16-18hr");
		expressionStages.add("embryo 18-20hr");
		expressionStages.add("embryo 20-22hr");
		expressionStages.add("embryo 22-24hr");
		expressionStages.add("embryonic 1182-4H");
		expressionStages.add("embryonic GM2");
		expressionStages.add("embryonic Kc167");
		expressionStages.add("embryonic S1");
		expressionStages.add("embryonic S3");
		expressionStages.add("eye-antennal disc ML-DmD11");
		expressionStages.add("haltere disc ML-DmD17-c3");
		expressionStages.add("larva L1");
		expressionStages.add("larva L2");
		expressionStages.add("larva L3 12hr old");
		expressionStages.add("larva L3 late, Zn 5mM");
		expressionStages.add("larva L3 puffstage 1-2");
		expressionStages.add("larva L3 puffstage 3-6");
		expressionStages.add("larva L3 puffstage 7-9");
		expressionStages.add("larva L3, Caffeine 1.5mg/ml");
		expressionStages.add("larva L3, Cd 12hr");
		expressionStages.add("larva L3, Cd 6hr");
		expressionStages.add("larva L3, Cu 0.5mM");
		expressionStages.add("larva L3, EtOH 10");
		expressionStages.add("larva L3, EtOH 2.5");
		expressionStages.add("larva L3, EtOH 5");
		expressionStages.add("larva L3, Rotenone 2?g");
		expressionStages.add("larva L3, Rotenone 8?g");
		expressionStages.add("leg disc CME L1");
		expressionStages.add("mixed discs ML-DmD4-c1");
		expressionStages.add("ovary OSC");
		expressionStages.add("ovary OSS");
		expressionStages.add("ovary fGS/OSS");
		expressionStages.add("tumorous blood cells mbn2");
		expressionStages.add("white prepupae new");
		expressionStages.add("wing disc CME-W2");
		expressionStages.add("wing disc ML-DmD16-c3");
		expressionStages.add("wing disc ML-DmD21");
		expressionStages.add("wing disc ML-DmD32");
		expressionStages.add("wing disc ML-DmD8");
		expressionStages.add("wing disc ML-DmD9");
		return expressionStages;
	}
}
