
package edu.ilstu.biology.flytranscriptionwebapp.transferobject;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@Generated("Generated by http://www.jsonschema2pojo.org/ using the json result from http://iodocs.apps.intermine.org/flymine/docs#/ws-query-results/POST/query/results using query from queries.properties")
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({ "rootClass", "modelName", "start", "views", "columnHeaders", "results", "executionTime",
		"wasSuccessful", "error", "statusCode" })
public class GeneIDInformationTO {

	@JsonProperty("rootClass")
	private String rootClass;
	@JsonProperty("modelName")
	private String modelName;
	@JsonProperty("start")
	private Integer start;
	@JsonProperty("views")
	private List<String> views = null;
	@JsonProperty("columnHeaders")
	private List<String> columnHeaders = null;
	@JsonProperty("results")
	private List<GeneIDInformationResultTO> results = null;
	@JsonProperty("executionTime")
	private String executionTime;
	@JsonProperty("wasSuccessful")
	private Boolean wasSuccessful;
	@JsonProperty("error")
	private Object error;
	@JsonProperty("statusCode")
	private Integer statusCode;
	@JsonIgnore
	private Map<String, Object> additionalProperties = new HashMap<String, Object>();

	@JsonProperty("rootClass")
	public String getRootClass() {
		return rootClass;
	}

	@JsonProperty("rootClass")
	public void setRootClass(String rootClass) {
		this.rootClass = rootClass;
	}

	@JsonProperty("modelName")
	public String getModelName() {
		return modelName;
	}

	@JsonProperty("modelName")
	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	@JsonProperty("start")
	public Integer getStart() {
		return start;
	}

	@JsonProperty("start")
	public void setStart(Integer start) {
		this.start = start;
	}

	@JsonProperty("views")
	public List<String> getViews() {
		return views;
	}

	@JsonProperty("views")
	public void setViews(List<String> views) {
		this.views = views;
	}

	@JsonProperty("columnHeaders")
	public List<String> getColumnHeaders() {
		return columnHeaders;
	}

	@JsonProperty("columnHeaders")
	public void setColumnHeaders(List<String> columnHeaders) {
		this.columnHeaders = columnHeaders;
	}

	@JsonProperty("results")
	public List<GeneIDInformationResultTO> getResults() {
		return results;
	}

	@JsonProperty("results")
	public void setResults(List<GeneIDInformationResultTO> results) {
		this.results = results;
	}

	@JsonProperty("executionTime")
	public String getExecutionTime() {
		return executionTime;
	}

	@JsonProperty("executionTime")
	public void setExecutionTime(String executionTime) {
		this.executionTime = executionTime;
	}

	@JsonProperty("wasSuccessful")
	public Boolean getWasSuccessful() {
		return wasSuccessful;
	}

	@JsonProperty("wasSuccessful")
	public void setWasSuccessful(Boolean wasSuccessful) {
		this.wasSuccessful = wasSuccessful;
	}

	@JsonProperty("error")
	public Object getError() {
		return error;
	}

	@JsonProperty("error")
	public void setError(Object error) {
		this.error = error;
	}

	@JsonProperty("statusCode")
	public Integer getStatusCode() {
		return statusCode;
	}

	@JsonProperty("statusCode")
	public void setStatusCode(Integer statusCode) {
		this.statusCode = statusCode;
	}

	@JsonAnyGetter
	public Map<String, Object> getAdditionalProperties() {
		return this.additionalProperties;
	}

	@JsonAnySetter
	public void setAdditionalProperty(String name, Object value) {
		this.additionalProperties.put(name, value);
	}

}
