
package edu.ilstu.biology.flytranscriptionwebapp.transferobject;

import java.util.HashMap;
import java.util.Map;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@Generated("Generated by http://www.jsonschema2pojo.org/ using the json result from http://iodocs.apps.intermine.org/flymine/docs#/ws-query-results/POST/query/results using query from queries.properties")
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "objectId",
    "value",
    "class"
})
public class GeneIDInformationSynonymTO {

    @JsonProperty("objectId")
    private Integer objectId;
    @JsonProperty("value")
    private String value;
    @JsonProperty("class")
    private String _class;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("objectId")
    public Integer getObjectId() {
        return objectId;
    }

    @JsonProperty("objectId")
    public void setObjectId(Integer objectId) {
        this.objectId = objectId;
    }

    @JsonProperty("value")
    public String getValue() {
        return value;
    }

    @JsonProperty("value")
    public void setValue(String value) {
        this.value = value;
    }

    @JsonProperty("class")
    public String getClass_() {
        return _class;
    }

    @JsonProperty("class")
    public void setClass_(String _class) {
        this._class = _class;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

}
